<?php

/**
 * This is the model base class for the table "Status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "Status" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $SID
 * @property integer $UID
 * @property string $UPDATE_TIME
 * @property string $CONTENT
 *
 */
abstract class BaseStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Status|Statuses', $n);
	}

	public static function representingColumn() {
		return 'UPDATE_TIME';
	}

	public function rules() {
		return array(
			array('UID, CONTENT', 'required'),
			array('UID', 'numerical', 'integerOnly'=>true),
			array('SID, UID, UPDATE_TIME, CONTENT', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'SID' => Yii::t('app', 'Sid'),
			'UID' => null,
			'UPDATE_TIME' => Yii::t('app', 'Update Time'),
			'CONTENT' => Yii::t('app', 'Content'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('SID', $this->SID);
		$criteria->compare('UID', $this->UID);
		$criteria->compare('UPDATE_TIME', $this->UPDATE_TIME, true);
		$criteria->compare('CONTENT', $this->CONTENT, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}